# Array of all dotfiles, for example .bashrc
# Put them in array without leading dot. Directories are fine too
# All those arrays are used only one time (at initial deploy)

# generic stuff deployed everywhere
genenv=(
          ackrc
          agents/skills
          bash_profile
          bashrc
          config/htop
          config/kitty
          config/mc
          config/mise
          config/tmux
          gemrc
          gitconfig
          gitignore_global
          htoprc
          mailcap
          mutt
          muttrc
          screenrc
          tigrc
          vim
          vimrc
          zshrc
        )

# linux-only dotfiles
linuxenv=(
            config/awesome
            config/openbox
            config/tint2
            dircolors
            gvimrc
            toprc
            Xdefaults
          )

# os x only stuff
osxenv=(
          hammerspoon
        )

mise_version="v2026.2.10"
