#!/usr/bin/env bash

# Simple shell script for symlinking all files from .rc dir to home directory
# Also upgrades, cleanups homebrew and similar stuff in single command
# Actually absurdly ugly, but hey, it works! Somehow.

#source config
source ~/.rc/envmgr.conf

# Function to symlink dotfiles
# Checking if OS is Linux (GNU coreutils), if not, we assume OS uses BSD utils
symlink() {
  if [[ $(uname) == "Linux" ]]; then
    ln -sfvn ${1} ${2}
  else
    ln -sfvh ${1} ${2}
  fi
}

case "${1}" in

  env)
    echo "Deploying environment"
    cd ~/.rc || exit
    echo "Deploying dotfiles from $(pwd) to ${HOME}"
    if [[ "${OSTYPE}" =~ ^linux ]]; then
      dotdirs=( .config .local/share )
      for dir in "${dotdirs[@]}"; do
        if [[ ! -d ~/${dir} ]]; then
          mkdir -p ~/${dir}
        fi
      done
      dotfiles=("${dotfiles[@]}" "${linuxenv[@]}")
    fi
    for file in "${dotfiles[@]}"; do
      symlink ~/.rc/.${file} ~/.${file}
    done
    symlink ~/.rc/envmgr ~/.rc/.bin/envmgr
    cd - >&/dev/null || exit 1
    echo "Finished!"
    echo "Installing vim plugins"
    vim +PlugInstall +qall
    echo "Finished!"
  ;;

  # Install rb/py/node-env. Used just one time.
  # I can do that manually in 5m, but i'm too lazy.
  # TODO: add cleanup of old versions, maybe as separate func
  devenv)
    #install asdf
    if [[ ! -d "$HOME/.asdf" ]]; then
      git clone https://github.com/asdf-vm/asdf.git ~/.asdf
    else
      cd ~/.asdf && git pull
    fi
    #init asdf
    source ~/.rc/sh.d/S01_env
    #install plugins
    for lang in "${asdf_plugins[@]}"; do
      asdf plugin-add ${lang}
    done
    #setup default packages
    for gem in "${gems[@]}"; do
      grep -sq ${gem} ~/.default-gems || echo ${gem} >> ~/.default-gems
    done
    for egg in "${eggs[@]}"; do
      grep -sq ${egg} ~/.default-eggs || echo ${egg} >> ~/.default-eggs
    done
    for npm_package in "${npms[@]}"; do
      grep -sq ${npm_package} ~/.default-npm-packages || echo ${npm_package} >> ~/.default-npm-packages
    done
    #install latest versions of langs
    #nodejs verifies signatures, assuming trusted environment
    #FIXME: support GPG verification for nodejs and python
    for lang in "${asdf_plugins[@]}"; do
      latest_version=$(asdf list-all ${lang} install -l | sort -V | grep -v '[a-z]' | tail -1)
      NODEJS_CHECK_SIGNATURES=no asdf install ${lang} ${latest_version}
      asdf global ${lang} ${latest_version}
    done
  ;;

  osx)
    cd ~/.rc || exit
    echo "Installing homebrew and favourite packages"
    #probably i should migrate to manual install.
    #Running (even respected) scripts from interwebs is stupid.
    if hash brew 2>/dev/null; then
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    brew bundle
  ;;

  nuke)
    echo "Cleaning up env"
    echo "Removing dotfiles"
    for file in "${dotfiles[@]}"; do
      rm -vf ~/.${file}
    done
    echo "Cleaning up devenv"
    rm -rvf ~/.asdf
    echo "Removing history"
    rm -vf ~/.zsh-history
    rm -vf ~/.bash_history
    echo "Removing dotfiles directory"
    rm -rf ~/.rc
  ;;

  maid)
    echo "Updating dotfiles repo"
    git -C ~/.rc pull
    echo "Cleaning up outdated symlinks"
    find -L $HOME -maxdepth 1 -type l -exec rm -i {} +
    if hash brew 2>/dev/null; then
      echo "Updating & cleaning up homebrew"
      brew update
      brew upgrade
      brew cleanup
      brew prune
      if [[ $(brew cask outdated) ]]; then
        echo "Updating homebrew casks"
        brew cask reinstall $(brew cask outdated)
        brew cask cleanup
      fi
      echo "Done"
    fi
    # Update asdf
    if [[ -d ~/.asdf ]]; then
      asdf update
      asdf plugin-update --all
    fi
    if hash mas 2>/dev/null && [ $(sw_vers | grep ProductVersion | cut -c20-21) -lt 13 ]; then
      echo "Updating mac app store apps"
      mas upgrade
    fi
    if hash vim 2>/dev/null; then
      echo "Upgrading vim bundles"
      vim +PlugUpdate +PlugUpgrade +PlugClean +qall
    fi
  ;;

  *)
    echo "Command list:"
    echo "env - symlink dotfiles"
    echo "devenv - install pyenv + rbenv + nodenv"
    echo "homebrew - install homebrew and favourite packages"
    echo "nuke - remove (almost) everything installed by envmgr"
    echo "maid - upgrade homebrew and devenv"
esac
