# Array of all dotfiles, for example .bashrc
# Put them in array without leading dot. Directories are fine too
# All those arrays are used only one time (at initial deploy)

# generic stuff deployed everywhere
genenv=(
          ackrc
          agents/skills
          bash_profile
          bashrc
          config/git
          config/htop
          config/kitty
          config/mc
          config/mise
          config/mutt
          config/tig
          config/gem
          config/htop
          config/zsh
          config/bash
          config/nvim
          config/tmux
          config/screen
          config/mailcap
          config/topgrade.toml
          vim
          vimrc
          zshenv
        )

# linux-only dotfiles
linuxenv=(
            config/awesome
            config/openbox
            config/tint2
            dircolors
            gvimrc
            toprc
            Xdefaults
          )

# os x only stuff
osxenv=(
          hammerspoon
        )

# Majority of apps will pre-create those folders
# Shells, however, won't
prerun_dirs=(
              $HOME/.config
              $HOME/.local/{cache/{zsh,bash},share,state/{zsh,bash}}
            )

outdatedenv=(
              gitconfig
              htoprc
              muttrc
              mutt
              tigrc
              gemrc
              zshrc
              screenrc
              mailcap
            )

mise_version="v2026.7.11"
