# This is my 'staging' area for apps i want to try to not clutter main config
# Main config only keeps stuff i actually use
[tools]
# ---Github repositories ---
"github:anomalyco/opencode" = "latest"
"github:charmbracelet/glow" = "latest"
"github:dandavison/delta" = "latest"
"github:deusdata/codebase-memory-mcp" = "latest"
"github:getzola/zola" = "latest"
"github:kenn-io/agentsview" = "latest"
"github:kenn-io/kata" = "latest"
"github:kenn-io/roborev" = "latest"
"github:modem-dev/hunk" = "latest"
"github:neurosnap/zmx" = "latest"
"github:nolabs-ai/nono" = "latest"
"github:projectdiscovery/httpx" = "latest"
"github:schemacrawler/schemacrawler" = "latest"
"github:sinelaw/fresh" = "latest"
"github:sxyazi/yazi" = "latest"
"github:vmware-tanzu/sonobuoy" = "latest"
