# This is my 'staging' area for apps i want to try to not clutter main config
# Main config only keeps stuff i actually use
[tools]
# ---Github repositories ---
"github:anomalyco/opencode" = "latest"
"github:charmbracelet/glow" = "latest"
"github:cilium/cilium-cli" = "latest"
"github:colbymchenry/codegraph" = "latest"
"github:dandavison/delta" = "latest"
"github:deusdata/codebase-memory-mcp" = "latest"
"github:dicklesworthstone/destructive_command_guard" = "latest"
"github:entireio/cli" = "latest"
"github:gastownhall/beads" = "latest"
"github:getzola/zola" = "latest"
"github:hmans/beans" = "latest"
"github:kenn-io/agentsview" = "latest"
"github:kenn-io/kata" = "latest"
"github:kenn-io/roborev" = "latest"
"github:kubie-org/kubie" = "latest"
"github:modem-dev/hunk" = "latest"
"github:nao1215/gup" = "latest"
"github:neurosnap/zmx" = "latest"
"github:nolabs-ai/nono" = "latest"
"github:orange-opensource/hurl" = "latest"
"github:quietpublish/mardi-gras" = "latest"
"github:rhysd/actionlint" = "latest"
"github:sinelaw/fresh" = "latest"
"github:starship/starship" = "latest"
"github:sxyazi/yazi" = "latest"
"github:vmware-tanzu/sonobuoy" = "latest"
