# thanks to https://github.com/hanndoddi/dotfiles/tree/main/.config/kitty for theme and statusbar

# BEGIN_KITTY_FONTS
font_family      family="PragmataPro Mono Liga"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0
# END_KITTY_FONTS

# disable ligatures when cursor is over symbol
disable_ligatures cursor

# increase scrollback buffers
scrollback_lines 10000
scrollback_pager_history_size 10

# hide mouse cursor while typing instantly
mouse_hide_wait -1

# send OS notification when command ends in inactive tab
notify_on_cmd_finish invisible

# fancy cursor effects
cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# cmd+u to switch between transparent modes
dynamic_background_opacity yes
map cmd+u remote_control_script ~/.config/kitty/toggle-opacity

# annoying things
update_check_interval 0
confirm_os_window_close 0

listen_on unix:/tmp/kitty
allow_remote_control socket-only

# tabs with style
tab_bar_edge top
tab_bar_margin_height 5.0 5.0
tab_bar_style custom
tab_powerline_style round
active_tab_foreground #FFFFFF
inactive_tab_foreground #888888
active_tab_background #458588
tab_title_template "{index}: {title}"
tab_bar_min_tabs 1

# option as alt
macos_option_as_alt yes

# iterm-style
map cmd+left previous_tab
map cmd+right next_tab
map cmd+backspace send_text all \x17

# theme definition
include theme.conf