[misc]
pre_sudo = false
disable = [
  # not needed
  "bun",
  "bun_packages",
  "containers",
  "node",
  # vim already handles it
  "nvim",
  # mise managed
  "rustup",
  "uv",
]
last = ["system"]
assume_yes = true
ask_retry = false
show_skipped = false
cleanup = true
notify_end = "always"
no_self_update = true

[vim]
force_plug_update = true