[settings]
minimum_release_age = "1d"
not_found_auto_install = false
experimental = true
trusted_config_paths = ["~/.rc/.config/mise"]

[settings.npm]
package_manager = "bun"

[settings.ruby]
compile = false
